#!/usr/bin/env python3
"""Generate wiki reference pages for every HubSpot module in the repo.

Usage: module_reference.py <repo_root> <wiki_root> [--dry-run]

Reads hubspot/<theme>/modules/**/*.module/{meta.json,fields.json} and writes
one Module-<theme>-<name>.md page per module plus a Modules.md index into the
wiki folder. Pages carry a generated marker; a page without the marker is
hand-written and is never overwritten. Pages for modules that no longer exist
are removed.
"""
import json
import sys
from pathlib import Path

MARKER = "<!-- generated by wiki-maintainer/module_reference.py - edits will be overwritten -->"


def short_theme(theme):
    return "q" if theme == "q-theme" else theme.replace("qoria-theme-", "")


def page_name(theme, rel):
    slug = rel.replace("\\", "/").removesuffix(".module").replace("/", "-").replace(" ", "-")
    return f"Module-{short_theme(theme)}-{slug}"


def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def load_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, ValueError):
        return None


def walk(fields, prefix, rows):
    for f in fields:
        path = prefix + str(f.get("name", "?"))
        notes = []
        if f.get("required"):
            notes.append("required")
        occ = f.get("occurrence")
        if occ:
            notes.append(f"repeats {occ.get('min') or 0}-{occ.get('max') or 'unlimited'}")
        choices = f.get("choices")
        if choices:
            vals = [c[0] if isinstance(c, list) else c for c in choices]
            notes.append("options: " + ", ".join(str(v) for v in vals))
        vis = f.get("visibility")
        if vis and vis.get("controlling_field"):
            notes.append(f"shown when `{vis['controlling_field']}` matches `{vis.get('controlling_value_regex', '?')}`")
        default = f.get("default")
        default = "" if default is None else json.dumps(default)
        if len(default) > 60:
            default = default[:57] + "..."
        rows.append((f.get("label", ""), path, f.get("type") or "group", default, "; ".join(notes)))
        if f.get("children"):
            walk(f["children"], path + ".", rows)


def render(theme, rel, mod_dir):
    meta = load_json(mod_dir / "meta.json") or {}
    fields = load_json(mod_dir / "fields.json")
    label = meta.get("label") or mod_dir.name.removesuffix(".module")
    lines = [MARKER, f"# {label}", ""]
    lines.append(f"- **Path:** `hubspot/{theme}/modules/{rel}`")
    lines.append(f"- **Theme:** {theme}")
    if meta.get("host_template_types"):
        lines.append("- **Template types:** " + ", ".join(meta["host_template_types"]))
    lines.append(f"- **Global module:** {'yes' if meta.get('global') else 'no'}")
    if meta.get("is_available_for_new_content") is False:
        lines.append("- **Available for new content:** no")
    present = [n for n in ("module.html", "module.css", "module.js") if (mod_dir / n).exists()]
    lines.append("- **Files:** " + ", ".join(present))
    for key, title in (("css_assets", "CSS assets"), ("js_assets", "JS assets")):
        assets = [a.get("path", "") for a in meta.get(key, [])]
        if assets:
            lines.append(f"- **{title}:** " + ", ".join(f"`{a}`" for a in assets))
    lines += ["", "## Fields", ""]
    if fields is None:
        lines.append("_fields.json is missing or could not be parsed._")
    elif not fields:
        lines.append("_No fields._")
    else:
        rows = []
        walk(fields, "", rows)
        lines += ["| Label | Field | Type | Default | Notes |", "| --- | --- | --- | --- | --- |"]
        lines += ["| " + " | ".join(cell(c) for c in r) + " |" for r in rows]
    return label, "\n".join(lines) + "\n"


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    dry = "--dry-run" in sys.argv
    if len(args) != 2:
        sys.exit(__doc__)
    repo, wiki = Path(args[0]), Path(args[1])
    wanted, index, written, skipped = {}, {}, 0, []
    for theme_dir in sorted((repo / "hubspot").iterdir()):
        mods = theme_dir / "modules"
        if not mods.is_dir():
            continue
        for mod_dir in sorted(mods.rglob("*.module")):
            rel = mod_dir.relative_to(mods).as_posix()
            name = page_name(theme_dir.name, rel)
            label, text = render(theme_dir.name, rel, mod_dir)
            wanted[name] = text
            index.setdefault(theme_dir.name, []).append((name, label, rel))
    for name, text in wanted.items():
        target = wiki / f"{name}.md"
        if target.exists() and MARKER not in target.read_text(encoding="utf-8"):
            skipped.append(name)
            continue
        if not dry:
            target.write_text(text, encoding="utf-8", newline="\n")
        written += 1
    lines = [MARKER, "# Modules", "", f"{sum(len(v) for v in index.values())} modules across {len(index)} themes. Each page lists the module's files, assets and fields.", ""]
    for theme, items in index.items():
        lines += [f"## {theme}", "", "| Module | Label |", "| --- | --- |"]
        lines += [f"| [{cell(rel)}]({name}) | {cell(label)} |" for name, label, rel in items]
        lines.append("")
    if not dry:
        (wiki / "Modules.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    stale = [p.stem for p in wiki.glob("Module-*.md") if p.stem not in wanted and MARKER in p.read_text(encoding="utf-8")]
    for s in stale:
        if not dry:
            (wiki / f"{s}.md").unlink()
    print(f"{'would write' if dry else 'wrote'} {written} module pages + Modules.md; removed {len(stale)} stale; skipped {len(skipped)} hand-written")
    for s in skipped:
        print(f"  skipped (hand-written): {s}")


if __name__ == "__main__":
    main()
