name: Deploy HubSpot Theme - Sandbox

on:
  push:
    branches:
      - sandbox


jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: sandbox

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HubSpot Deploy Action Sandbox
        uses: HubSpot/hubspot-cms-deploy-action@v2.1.0
        with:
          account_id: ${{ vars.HS_ACCT_ID_ANZ }}
          personal_access_key: ${{ secrets.HS_PAK_KS }}
          src_dir: hubspot
          dest_dir: /